[package]
name = "exchange-collection-binance"
version = "2.2.0"
edition = "2021"

[dependencies.exchange-collection-binance-rest]
version = "1.1.0"
path = "src/rest"

[dependencies.exchange-collection-binance-ws]
version = "1.1.0"
path = "src/ws"
