name: Sync Generated Crate

on:
  push:
    branches:
      - release

jobs:
  sync_crate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main repository
        uses: actions/checkout@v3

      - name: install rust
        uses: dtolnay/rust-toolchain@stable

      - name: run the codegen and build the workspace
        run: cargo build

      - name: Checkout generated crate repo
        uses: actions/checkout@v4
        with:
          repository: kanekoshoyu/exchange-collection-rust
          token: ${{ secrets.PAK_TOKEN }}
          path: /tmp/exchange-collection-rust

      - name: sync generated crate
        run: rsync -av --delete target/rust/ target/generated-crate-repo/

      - name: commit and push changes
        run: |
          cd target/generated-crate-repo
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Automated update of generated crate"
          git pull --rebase origin main || echo "No changes to pull"
          git push origin main