name: Sync Generated Crate

on:
  push:
    branches:
      - release

jobs:
  sync_crate:
    runs-on: ubuntu-latest
    steps:
      - name: Install asyncapi code generator
        run: npm install -g @openapitools/openapi-generator-cli

      - name: Install asyncapi code generator
        run: npm install -g @asyncapi/generator

      - name: checkout main repository
        uses: actions/checkout@v3

      - name: install rust
        uses: dtolnay/rust-toolchain@stable

      - name: build codegen
        run: cargo build

      - name: list out current dir
        run: ls -l

      - name: run codegen and build workspace
        run: cargo run

      - name: list out target rust code
        run: find target/rust -maxdepth 4 -print

      - name: clone generated crate repo
        run: git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kanekoshoyu/exchange-collection-rust.git tmp/target

      - name: sync generated crate
        run: rsync -av --delete target/rust/ tmp/target

      - name: commit and push changes
        run: |
          cd tmp/target
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated update of generated crate"
            git push origin main
          fi
