name: Sync Generated Crate

on:
  push:
    branches:
      - release

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  sync_crate:
    runs-on: ubuntu-latest
    steps:
      - name: Install asyncapi code generator
        run: npm install -g @openapitools/openapi-generator-cli

      - name: Install asyncapi code generator
        run: npm install -g @asyncapi/generator

      - name: checkout main repository
        uses: actions/checkout@v3

      - name: install rust
        uses: dtolnay/rust-toolchain@stable

      - name: build codegen
        run: cargo build

      - name: list out current dir
        run: ls -l

      - name: run codegen and build workspace
        run: cargo run

      - name: list out target rust code
        run: find target/rust -maxdepth 4 -print

      - name: clone generated crate repo
        run: git clone https://x-access-token:${{ secrets.PAK_TOKEN }}@github.com/kanekoshoyu/exchange-collection-rust.git /tmp/exchange-collection-rust

      - name: sync generated crate
        run: |
          mv target/rust/* /tmp/exchange-collection-rust

      - name: commit and push changes
        run: |
          cd /tmp/exchange-collection-rust
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          fi
          git commit -m "Automated update of generated crate"
          git pull --rebase origin main || echo "No changes to pull"
          git push origin main
